<?php
include dirname(__DIR__).'/header.phtml';
?>
    
<div class="wrapper">
    <form method="post" class="form-signin">       
        <h2 class="form-signin-heading">Registrieren</h2>
        <input type="text" class="form-control" name="username" placeholder="Benutzername"/>
        <input type="password" class="form-control" name="pw" placeholder="Passwort"/>
        <input type="hidden" name="controller" value="user" />
        <input type="hidden" name="do" value="checkLogin" />
        <br>
        <input type="submit" name="submit" value="Registrieren" >
    </form>
</div>

<?php include dirname(__DIR__).'/footer.phtml'; ?>
