<!DOCTYPE html>
<html>
    <head>
        <title>Mitgliederverwaltung</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="CSS/style.css" rel="stylesheet" type="text/css" />
        <link href="CSS/style_grid.css" rel="stylesheet" type="text/css"/>
    </head>
    <body>
        <header>
            <div class="container">
                <nav>
                    <h1>Überschrift</h1>
                    <ul>
                        <li><a href="?controller=User&do=showStart">Willkommen</a></li>
                        <li><a href="?controller=Default&do=testFunction1">Punkt 2</a></li>
                        <li><a href="?controller=Default&do=testFunction2">Punkt 3</a></li>
                        <li><a href="#">Punkt 4</a></li>
                    </ul>
                </nav>
            </div>
        </header>
        <div id="wrapper">
            <main>