<!-- von timothy görzen -->

<?php
include dirname(__DIR__).'/header.phtml';
?>

<!--
<form method="post">
    Vorname: <input type="text" name="vorname" /><br>
    Nachnahme: <input type="text" name="nachname" /><br>
    Benutzername: <input type="text" name="username" /><br>
    E-Mail: <input type="text" name="email" /><br>
    Passwort: <input type="password" name="pw" /><br>
    <input type="hidden" name="controller" value="user" />
    <input type="hidden" name="do" value="showLogin" />
    <input type="submit" name="submit" value="Registrieren" ></br>
    <a href="?controller=User&do=showStart">registrierung</a>
</form>
-->

<div class="wrapper">
    <form method="post" class="form-signin">       
        <h2 class="form-signin-heading">Registrieren</h2>
        <input type="text" class="form-control" name="vorname" placeholder="Vorname"/><br>
        <input type="text" class="form-control" name="nachname" placeholder="Nachname"/><br>
        <input type="text" class="form-control" name="username" placeholder="Benutzername"/><br>
        <input type="text" class="form-control" name="email" placeholder="E-Mail"/><br>
        <input type="password" class="form-control" name="pw" placeholder="Passwort"/><br>
        <input type="hidden" name="controller" value="user" />
        <input type="hidden" name="do" value="showLogin" />
        <input type="submit" name="submit" value="Registrieren" ></br>
    </form>
</div>

<?php include dirname(__DIR__).'/footer.phtml'; ?>