<?php
include dirname(__DIR__).'/header.phtml';
?>

<!--
<form method="post">
    Benutzername: <input type="text" name="username" /><br>
    Passwort: <input type="password" name="pw" /><br>
    <input type="hidden" name="controller" value="user" />
    <input type="hidden" name="do" value="showLogin" />
    <input type="submit" name="submit" value="Anmelden" ></br>
    Noch nicht registriert? hier geht es zur <a href="?controller=User&do=showRegistration">registrierung</a>
</form>
-->

<div class="wrapper">
    <form method="post" class="form-signin">       
        <h2 class="form-signin-heading">Login</h2>
        <input type="text" class="form-control" name="username" placeholder="Benutzername"/>
        <input type="password" class="form-control" name="pw" placeholder="Passwort"/>
        <input type="hidden" name="controller" value="user" />
        <input type="hidden" name="do" value="showLogin" />
        <br>
        <input type="submit" name="submit" value="Anmelden" >
        <br>
        <br>
        Noch kein Accoount? Registrieren sie sich <a href="?controller=User&do=showRegistration">hier.</a>
    </form>
</div>

<?php include dirname(__DIR__).'/footer.phtml'; ?>