<!-- von timothy görzen -->

<?php
include dirname(__DIR__).'/header.phtml';
?>
<div class="wrapper">
    <form method="post" class="form-signin">
        <h1>Profil von <?php echo $_SESSION["username"]?></h1> </br>
        <p>Vorname: <?php echo $_SESSION["firstname"]?></p> 
        <p>Nachname: <?php echo $_SESSION["lastname"]?></p> 
        <p>Trainer: <?php echo $_SESSION["isTrainer"]?></p>
        <p>Mitarbeiter: <?php echo $_SESSION["isClerk"]?></p>
    </form>
</div>

<?php include dirname(__DIR__).'/footer.phtml'; ?>