<!DOCTYPE html>
<html>
    <head>
        <title>Mitgliederverwaltung</title>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="CSS/style.css" rel="stylesheet" type="text/css" />
        <link href="CSS/style_grid.css" rel="stylesheet" type="text/css"/>
    </head>
        <nav id="header-nav">
			<div class="container" id="desktop-nav">
				<div class="row">
					<div class="col-6">
						<a href="?controller=Default&do=showStart" class="logo-link">
							<img src="./img/logo.png" alt="logo">
						</a>

						<ul>
                            <li><a href="?controller=Default&do=showStart">Willkommen</a></li>
                            <li><a href="?controller=User&do=showLogin">Login</a></li>
                            <li><a href="#">Punkt 3</a></li>
                            <li><a href="#">Punkt 4</a></li>
						</ul>

					</div>
				</div>
			</div>
		</nav>
    <main>
